// <auto-generated />
namespace HR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dbmodel6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbmodel6));
        
        string IMigrationMetadata.Id
        {
            get { return "201510100717001_dbmodel6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
